@props([
    'status' => '',
])

@php
    $normalized = trim($status ?? '');
    
    // Status color configurations (Executive Light Mode SaaS standard)
    $configs = [
        'Demande' => [
            'bg' => 'bg-sky-50',
            'text' => 'text-sky-700',
            'border' => 'border-sky-200',
            'dot' => 'bg-sky-500',
            'label' => 'Demande reçue',
            'pulse' => false,
        ],
        'En attente' => [
            'bg' => 'bg-amber-50',
            'text' => 'text-amber-700',
            'border' => 'border-amber-200',
            'dot' => 'bg-amber-500',
            'label' => 'En attente',
            'pulse' => false,
        ],
        'Planifiee' => [
            'bg' => 'bg-amber-50',
            'text' => 'text-amber-700',
            'border' => 'border-amber-200',
            'dot' => 'bg-amber-500',
            'label' => 'Planifiée',
            'pulse' => false,
        ],
        'Planifiée' => [
            'bg' => 'bg-amber-50',
            'text' => 'text-amber-700',
            'border' => 'border-amber-200',
            'dot' => 'bg-amber-500',
            'label' => 'Planifiée',
            'pulse' => false,
        ],
        'Affectee' => [
            'bg' => 'bg-violet-50',
            'text' => 'text-violet-700',
            'border' => 'border-violet-200',
            'dot' => 'bg-violet-500',
            'label' => 'Affectée',
            'pulse' => false,
        ],
        'Affectée' => [
            'bg' => 'bg-violet-50',
            'text' => 'text-violet-700',
            'border' => 'border-violet-200',
            'dot' => 'bg-violet-500',
            'label' => 'Affectée',
            'pulse' => false,
        ],
        'Acceptee' => [
            'bg' => 'bg-indigo-50',
            'text' => 'text-indigo-700',
            'border' => 'border-indigo-200',
            'dot' => 'bg-indigo-500',
            'label' => 'Acceptée',
            'pulse' => false,
        ],
        'Acceptée' => [
            'bg' => 'bg-indigo-50',
            'text' => 'text-indigo-700',
            'border' => 'border-indigo-200',
            'dot' => 'bg-indigo-500',
            'label' => 'Acceptée',
            'pulse' => false,
        ],
        'En cours' => [
            'bg' => 'bg-emerald-50',
            'text' => 'text-emerald-700',
            'border' => 'border-emerald-300',
            'dot' => 'bg-emerald-500',
            'label' => 'En cours',
            'pulse' => true,
        ],
        'Suspendue' => [
            'bg' => 'bg-amber-50',
            'text' => 'text-amber-800',
            'border' => 'border-amber-200',
            'dot' => 'bg-amber-500',
            'label' => 'Suspendue',
            'pulse' => false,
        ],
        'Reportee' => [
            'bg' => 'bg-slate-100',
            'text' => 'text-slate-700',
            'border' => 'border-slate-200',
            'dot' => 'bg-slate-400',
            'label' => 'Reportée',
            'pulse' => false,
        ],
        'Reportée' => [
            'bg' => 'bg-slate-100',
            'text' => 'text-slate-700',
            'border' => 'border-slate-200',
            'dot' => 'bg-slate-400',
            'label' => 'Reportée',
            'pulse' => false,
        ],
        'Partiellement realisee' => [
            'bg' => 'bg-orange-50',
            'text' => 'text-orange-700',
            'border' => 'border-orange-200',
            'dot' => 'bg-orange-500',
            'label' => 'Partiellement réalisée',
            'pulse' => false,
        ],
        'Client absent' => [
            'bg' => 'bg-rose-50',
            'text' => 'text-rose-700',
            'border' => 'border-rose-200',
            'dot' => 'bg-rose-500',
            'label' => 'Client absent',
            'pulse' => false,
        ],
        'Materiel manquant' => [
            'bg' => 'bg-orange-50',
            'text' => 'text-orange-700',
            'border' => 'border-orange-200',
            'dot' => 'bg-orange-500',
            'label' => 'Matériel manquant',
            'pulse' => false,
        ],
        'Deuxieme visite requise' => [
            'bg' => 'bg-purple-50',
            'text' => 'text-purple-700',
            'border' => 'border-purple-200',
            'dot' => 'bg-purple-500',
            'label' => '2e visite requise',
            'pulse' => false,
        ],
        'Formulaire rempli' => [
            'bg' => 'bg-teal-50',
            'text' => 'text-teal-700',
            'border' => 'border-teal-200',
            'dot' => 'bg-teal-500',
            'label' => 'Formulaire rempli',
            'pulse' => false,
        ],
        'En attente validation' => [
            'bg' => 'bg-purple-50',
            'text' => 'text-purple-700',
            'border' => 'border-purple-200',
            'dot' => 'bg-purple-500',
            'label' => 'En validation',
            'pulse' => false,
        ],
        'Rejetee' => [
            'bg' => 'bg-rose-50',
            'text' => 'text-rose-700',
            'border' => 'border-rose-200',
            'dot' => 'bg-rose-500',
            'label' => 'Rejetée',
            'pulse' => false,
        ],
        'Rejetée' => [
            'bg' => 'bg-rose-50',
            'text' => 'text-rose-700',
            'border' => 'border-rose-200',
            'dot' => 'bg-rose-500',
            'label' => 'Rejetée',
            'pulse' => false,
        ],
        'Terminee' => [
            'bg' => 'bg-emerald-50',
            'text' => 'text-emerald-700',
            'border' => 'border-emerald-200',
            'dot' => 'bg-emerald-500',
            'label' => 'Terminée',
            'pulse' => false,
        ],
        'Terminée' => [
            'bg' => 'bg-emerald-50',
            'text' => 'text-emerald-700',
            'border' => 'border-emerald-200',
            'dot' => 'bg-emerald-500',
            'label' => 'Terminée',
            'pulse' => false,
        ],
        'Validee' => [
            'bg' => 'bg-emerald-100',
            'text' => 'text-emerald-800 font-bold',
            'border' => 'border-emerald-300',
            'dot' => 'bg-emerald-600',
            'label' => 'Validée',
            'pulse' => false,
        ],
        'Validée' => [
            'bg' => 'bg-emerald-100',
            'text' => 'text-emerald-800 font-bold',
            'border' => 'border-emerald-300',
            'dot' => 'bg-emerald-600',
            'label' => 'Validée',
            'pulse' => false,
        ],
        'Annulee' => [
            'bg' => 'bg-slate-100',
            'text' => 'text-slate-600',
            'border' => 'border-slate-200',
            'dot' => 'bg-slate-400',
            'label' => 'Annulée',
            'pulse' => false,
        ],
        'Annulée' => [
            'bg' => 'bg-slate-100',
            'text' => 'text-slate-600',
            'border' => 'border-slate-200',
            'dot' => 'bg-slate-400',
            'label' => 'Annulée',
            'pulse' => false,
        ],
        'En attente reafectation' => [
            'bg' => 'bg-rose-50',
            'text' => 'text-rose-700 font-semibold',
            'border' => 'border-rose-200',
            'dot' => 'bg-rose-500',
            'label' => 'Refus Technicien',
            'pulse' => true,
        ],
    ];

    $cfg = $configs[$normalized] ?? [
        'bg' => 'bg-slate-100',
        'text' => 'text-slate-700',
        'border' => 'border-slate-200',
        'dot' => 'bg-slate-400',
        'label' => $normalized ?: 'Inconnu',
        'pulse' => false,
    ];
@endphp

<span class="inline-flex items-center gap-1.5 px-2.5 py-0.5 rounded-full text-xs font-semibold tracking-normal border {{ $cfg['bg'] }} {{ $cfg['text'] }} {{ $cfg['border'] }}">
    <span class="w-1.5 h-1.5 rounded-full {{ $cfg['dot'] }} {{ $cfg['pulse'] ? 'animate-pulse' : '' }}"></span>
    <span>{{ $cfg['label'] }}</span>
</span>
